### ISSUE TITLE
HCS commands

### ISSUE THREAD

**Issue by calvinchengx** [hashgraph/hedera-cli#158]
Deliverables:
Working CLI commands like this:

```
create-topic
submit-message
     –topic-id 0.0.1234 “Hello, world”
read-messages –topic-id 0.0.1234
```

Tutorial on how to use CLI commands

Might not want to use "-" because it breaks the convention seen in the other existing commands.

**Comment by calvinchengx** [comment]
```
> hcs create topic
> hcs submit message --topic-id 0.0.1234 "Hello world"
> hcs read message --topic-id 0.0.1234
```

**Comment by calvinchengx** [comment]
```
> hcs create
> hcs submit --topic-id 0.0.1234 "Hello world"
> hcs read --topic-id 0.0.1234
```

**Comment by calvinchengx** [comment]
@enerestar proposed cli design for flags (options/params) as follows:-

**Creating a HCS topic**

```
# valid example commands
hcs create    
hcs create --memo "my defi application!"
hcs create -m "my defi application!"

# an ed25519 key pair will be generated and saved into `~/.hedera/[network]/topics/[random_name].json
hcs create --submit-key  
hcs create -k

# single command to do both
hcs create --memo "my defi application!" --submit-key
```

**Submitting a message to a HCS topic id**

```
hcs submit 0.0.140342 --message "hello world"
hcs submit 0.0.140342 -m "hello world" 
```

**Reading messages from a HCS topic id**

Uses the same flags as proposed in https://github.com/hashgraph/hedera-cli/issues/162#issuecomment-578464673

I will handle this as part of #162

**Comment by enerestar** [comment]
@calvinchengx  some thoughts

|   |   |   |   |   |
|---|---|---|---|---|
| `hcs create -d` (d = default)  | ConsensusTopicCreateTransaction()  |  -  |  -  | .execute()   |
| `hcs create -t` (t = topic)  | ConsensusTopicCreateTransaction()  | .setTopicMemo()  |  -  | .execute()   |  
| `hcs create -k` (k = key) | ConsensusTopicCreateTransaction()  |  -  | .setSubmitKey()  | .execute()   |  
|  `hcs create -t -k -y` (y = yes to keygen | ConsensusTopicCreateTransaction()  | .setTopicMemo()  | .setSubmitKey(keyGenerated)  | .execute()   | 
| `hcs create -t -k ` (prompts input) | ConsensusTopicCreateTransaction()  | .setTopicMemo()  | .setSubmitKey(keyProvided)  | .execute()  |

Because `ConsensusMessageSubmitTransaction().setTopicId(topicId).setMessage(message)`
`-m` flag might be confusing? Not sure how many bytes is allowed in setMessage vs setTopicMemo

**Comment by calvinchengx** [comment]
Looks okay.

Except for `hcs create`. There’s no concept of topic name. It’s our own misunderstanding.

Much like account create, no account name is persisted on server side. In hcs create, there’s also no concept of a topic name. We simply call hcs create and that’s it. The ledger returns us a topic id.

www.calvinx.com ( http://www.calvinx.com )
Stalk me! @ www.twitter.com/calvinchengx ( http://www.twitter.com/calvinchengx )

Sent via Superhuman iOS ( https://sprh.mn/?vip=calvin@calvinx.com )

**Comment by enerestar** [comment]
TODO
We should save the newly generated keys somewhere but 
1) can a hcs submit key be associate with a keypair that does not have an Hedera Account? probably yes.
2) we will need to save the keys in a [network][hcs][submitKeys] folder
3) while topics created to be save in [network][hcs][topics] folder, with the associated public key (if it exists) and topic id.

**Comment by calvinchengx** [comment]
www.calvinx.com ( http://www.calvinx.com )
Stalk me! @ www.twitter.com/calvinchengx ( http://www.twitter.com/calvinchengx )

Sent via Superhuman iOS ( https://sprh.mn/?vip=calvin@calvinx.com )

On Sun, Jan 26 2020 at 3:00 PM, Serene < notifications@github.com > wrote:

> 
> 
> 
> TODO
> We should save the newly generated keys somewhere but
> 
> * can a hcs submit key be associate with a keypair that does not have an
> Hedera Account? probably yes.
> 
> 

Yes. We are on the same page.

This is a generated key pair that has no association whatsoever with Hedera account keys.
